server:
  port: 19932


logging:
  level:
    com.jansora: debug



spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://mysql.jansora.app:3306/dev?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20