package com.jansora.demo.rule.drools;

//import com.jansora.demo.rule.drools.pom.delay.DelayProject;
//import java.time.LocalDateTime;
import java.time.Duration;

declare DelayProject

  delayDays : Long

      /**
       * 项目预期时间
       */
  expectedDate: java.time.LocalDateTime

    /**
     * 项目完成时间
     */
  completedDate: java.time.LocalDateTime
end

//规则rule1的注释，这是一个单行注释
rule "green"
    no-loop true
    lock-on-active true //锁住规则，防止重复触发
    when
        $project: DelayProject( Duration.between(completedDate, expectedDate).toDays() < 0)
    then
//        $project.setColor("green");
        System.out.println("rule1触发");
end